name       : libopenglrecorder
version    : 0.1.0
release    : 2
source     :
    - https://github.com/Benau/libopenglrecorder/archive/v0.1.0.tar.gz : a90a99c23f868636f77003a8dc6ffe6c3699fc2759c47df5dbd44ff8b42d2e4f
license    : BSD-3-Clause
component  : multimedia.library
summary    : A library allowing optional async readback OpenGL frame buffer with optional
    audio recording
description: |
    libopenglrecorder is a library allowing optional async readback OpenGL frame buffer with optional audio recording. It will do video and audio encoding together.
builddeps  :
    - pkgconfig(libpulse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
